class AppStrings {
  static String appname = 'Mediapp',
      bestDocapp = 'Best Doctor \n Appointment App',
      welcomeBack = 'Welcome Back!',
      weAreExcited = 'We are excited to have you back!',
      signUpNow =
          'Sign up now and start exploring all that our app has to offer',
      email = 'Email',
      emailHint = 'Enter your email...',
      password = 'password',
      passwordHint = 'Enter your password here...',
      fullname = 'Full Name',
      fullnameHint = 'Enter your name',
      confirmPassword = 'Confirm Password',
      forgetPassword = 'Forget Password',
      login = 'Login',
      signup = 'Signup',
      alreadyHaveAccount = 'Account have an account?',
      dontHaveAccount = 'Dont have an account?',
      search = 'Search Doctor',
      welcome = 'welcome',
      catagory = 'Catagory',
      doctor = 'Doctor Login',
      settings = 'Settings',
      changePassword = 'Change Password',
      termsCondition = 'Terms & Conditions',
      signOut = 'Signout',
      body = 'Body',
      ear = 'Ear',
      liver = 'Liver',
      lungs = 'Lungs',
      heart = 'Heart',
      kidney = 'Kidney';
}
