// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3V27TFloWtNlrlL7jJL70rEpS2Ehaby0',
    appId: '1:359796897924:web:6b9376b3663ac3f3fbaad1',
    messagingSenderId: '359796897924',
    projectId: 'mediappp',
    authDomain: 'mediappp.firebaseapp.com',
    storageBucket: 'mediappp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3W9_bybVQUkdmfVm5RUUBnBfEqY6xi3E',
    appId: '1:359796897924:android:56ae536b0dffe962fbaad1',
    messagingSenderId: '359796897924',
    projectId: 'mediappp',
    storageBucket: 'mediappp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIGZMLUb6J2xHY8r5JOAyzx6HkVJ87O_U',
    appId: '1:359796897924:ios:2ab09a0a9751cc19fbaad1',
    messagingSenderId: '359796897924',
    projectId: 'mediappp',
    storageBucket: 'mediappp.appspot.com',
    iosBundleId: 'com.example.mediapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIGZMLUb6J2xHY8r5JOAyzx6HkVJ87O_U',
    appId: '1:359796897924:ios:c5e8c23498c2d0adfbaad1',
    messagingSenderId: '359796897924',
    projectId: 'mediappp',
    storageBucket: 'mediappp.appspot.com',
    iosBundleId: 'com.example.mediapp.RunnerTests',
  );
}
